# Generated by Django 4.1.2 on 2022-10-25 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_account"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Account",
        ),
    ]
